name: emle

channels:
  - conda-forge

dependencies:
  - ambertools
  - ase
  - deepmd-kit
  - loguru
  - nnpops
  - pip
  - psutil
  - pygit2
  - pytorch
  - python
  - pyyaml
  - torchani
  - xtb-python
  - pip:
    - mace-torch
